<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="WIN-2AB1O2NOUBG" failures="1" tests="7" name="tests.LoginTests" time="74.811" errors="0" timestamp="2022-09-17T03:09:46 EEST" skipped="2">
  <testcase classname="tests.LoginTests" name="loginPositiveTest" time="10.013"/>
  <system-out/>
  <testcase classname="tests.LoginTests" name="loginNegativeFormatEmailTest" time="14.538">
    <failure message="No visibility element: //div[@fxlayoutalign=&#039;start center&#039;]//div" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: No visibility element: //div[@fxlayoutalign='start center']//div
at org.testng.Assert.fail(Assert.java:110)
at base.BasePage.waitUntilVisibilityOfElementLocated(BasePage.java:44)
at pages.LoginPageElements.errorPopup(LoginPageElements.java:34)
at pages.LoginPageHelper.assertions(LoginPageHelper.java:18)
at tests.LoginTests.loginNegativeFormatEmailTest(LoginTests.java:33)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
]]>
    </failure>
  </testcase> <!-- loginNegativeFormatEmailTest -->
  <system-out/>
  <testcase classname="tests.LoginTests" name="loginNegativePasswordTest" time="5.959"/>
  <system-out/>
  <testcase classname="tests.LoginTests" name="loginNegativeEmailTest" time="5.014"/>
  <system-out/>
  <testcase classname="tests.LoginTests" name="loginWithoutPasswordTest" time="10.026"/>
  <system-out/>
  <testcase classname="tests.LoginTests" name="loginNegativeFormatEmailTest" time="14.704">
    <skipped/>
  </testcase> <!-- loginNegativeFormatEmailTest -->
  <system-out/>
  <testcase classname="tests.LoginTests" name="loginNegativeFormatEmailTest" time="14.557">
    <skipped/>
  </testcase> <!-- loginNegativeFormatEmailTest -->
  <system-out/>
</testsuite> <!-- tests.LoginTests -->
